name: Build mosdns-x for NanoPi R3S

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
              zlib1g-dev file wget unzip zstd python3-pyelftools

      - name: Install Go 1.25.4
        run: |
          wget https://go.dev/dl/go1.25.4.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.25.4.linux-amd64.tar.gz
          echo "PATH=/usr/local/go/bin:$PATH" >> $GITHUB_ENV
          echo "GOTOOLCHAIN=local" >> $GITHUB_ENV

      - name: Download ImmortalWrt SDK (armvirt/64 for NanoPi R3S)
        run: |
          wget https://downloads.immortalwrt.org/releases/24.10.4/targets/rockchip/armv8/immortalwrt-sdk-24.10.4-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar --zstd -xf immortalwrt-sdk-24.10.4-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          SDK_DIR=$(find . -maxdepth 1 -type d -name "immortalwrt-sdk-*" | head -n 1)
          echo "Found SDK directory: $SDK_DIR"
          mv "$SDK_DIR" sdk

      - name: Prepare SDK
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add mosdns-x package
        run: |
          mkdir -p sdk/package/mosdnsx
          cp -f Makefile sdk/package/mosdnsx/

      - name: Build mosdns-x
        run: |
          cd sdk
          make defconfig
          make package/mosdnsx/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: mosdnsx-ipk
          path: sdk/bin/packages/*/*/mosdnsx*.ipk
