name: Build mosdns-x for NanoPi R3S

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
              zlib1g-dev file wget unzip zstd python3-pyelftools

      - name: Install Go 1.25.4
        run: |
          wget https://go.dev/dl/go1.25.4.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.25.4.linux-amd64.tar.gz
          echo "PATH=/usr/local/go/bin:$PATH" >> $GITHUB_ENV
          echo "GOTOOLCHAIN=local" >> $GITHUB_ENV

      - name: Download ImmortalWrt SDK (armvirt/64 for NanoPi R3S)
        run: |
          wget https://downloads.immortalwrt.org/releases/24.10.4/targets/rockchip/armv8/immortalwrt-sdk-24.10.4-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar --zstd -xf immortalwrt-sdk-24.10.4-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          SDK_DIR=$(find . -maxdepth 1 -type d -name "immortalwrt-sdk-*" | head -n 1)
          echo "Found SDK directory: $SDK_DIR"
          mv "$SDK_DIR" sdk

      - name: Prepare SDK
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add mosdns-x package
        run: |
          mkdir -p sdk/package/mosdns-x
          cat << 'EOF' > sdk/package/mosdns-x/Makefile
          include $(TOPDIR)/rules.mk
          
          PKG_NAME:=mosdns-x
          PKG_VERSION:=25.11.11
          PKG_RELEASE:=1
          
          PKG_SOURCE_PROTO:=git
          PKG_SOURCE_URL:=https://github.com/pmkol/mosdns-x.git
          PKG_SOURCE_VERSION:=HEAD
          PKG_MIRROR_HASH:=skip
          
          PKG_LICENSE:=GPL-3.0
          PKG_LICENSE_FILES:=LICENSE
          
          # 不使用 OpenWrt 的 go（版本太低）
          include $(INCLUDE_DIR)/package.mk
          
          define Package/mosdns-x
            SECTION:=net
            CATEGORY:=Network
            TITLE:=mosdns-x DNS server
            URL:=https://github.com/pmkol/mosdns-x
          endef
          
          define Package/mosdns-x/description
           Enhanced modular DNS server
          endef
          
          # 手动调用 system Go 1.25.4
          define Build/Compile
                  cd $(PKG_BUILD_DIR) && \
                  go build -trimpath -ldflags "-s -w" -o mosdns-x ./cmd/mosdnsx
          endef
          
          define Package/mosdns-x/install
                  $(INSTALL_DIR) $(1)/usr/bin
                  $(INSTALL_BIN) $(PKG_BUILD_DIR)/mosdns-x $(1)/usr/bin/mosdns-x
          endef
          
          $(eval $(call BuildPackage,mosdns-x))
          EOF

      - name: Build mosdns-x
        run: |
          cd sdk
          make defconfig
          make package/mosdns-x/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: mosdns-x-ipk
          path: sdk/bin/packages/*/*/mosdns-x*.ipk
